name: Deploy Hexo Blog

on:
  push:
    branches:
      - main # default branch

# 确保这段存在，且缩进正确
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # 必须为 false，否则后续部署步骤可能出错
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive

      - name: Use Bun
        uses:  oven-sh/setup-bun@v2
        with:
          # Ref: https://bun.sh/guides/runtime/cicd
          bun-version: "latest" # or "latest", "canary", <sha>

      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: Install Dependencies
        run: bun install

      - name: Build Hexo
        run: bun run hexo generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub 自动生成的 Token，无需手动设置
          publish_dir: ./public # Hexo 生成的静态文件目录
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
